name: Build distribution 📦

on:
  workflow_run:
    workflows: ["Changelog ⛰️"]
    types:
      - completed
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0

      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Package
        run: uv build

      - name: Check package
        run: uvx twine check --strict dist/*.whl

      - name: Store Wheel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.whl
