name: Changelog ⛰️

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and for pushing commits

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest --no-exec
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - name: Commit the Changelog
        run: |
          # For PRs, github.head_ref is the name of the head branch.
          # For pushes to main, github.ref_name is 'main'.
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          git checkout "$BRANCH_NAME"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          # Add the changelog file
          git add CHANGELOG.md
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit in CHANGELOG.md"
          else
            git commit -m "docs: Update changelog" -m "Generated by git-cliff for ${{ github.sha }}"
            # Push the changes
            # The GITHUB_TOKEN secret has write permissions to the repository
            git push origin "$BRANCH_NAME"
          fi
